version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependency
  ignore:
  - dependency-name: org.modelmapper:modelmapper
    versions:
    - 2.3.9
    - 2.4.0
    - 2.4.1
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.zonky.test:embedded-database-spring-test
    versions:
    - 1.6.2
